### ISSUE TITLE
HTTPS Certificate question

### ISSUE THREAD

**Issue by timothechauvet** [bkk87/oci-nextcloud-podman#1]
Hello, I have issues with the [Load balancing part](https://github.com/bkk87/oci-nextcloud-podman/blob/main/modules/nextcloud/load_balancer.tf) where I get an index error fetching certificates since there are none in my account. I can't seem to find any `oci_load_balancer_certificate` instance on the config that lets me wonder if we don't have to import it manually, is that correct ?

`│ Error: Invalid index
│ 
│   on modules/nextcloud/load_balancer.tf line 72, in resource "oci_load_balancer_listener" "https_443_ingress":
│   72:     certificate_name        = data.oci_load_balancer_certificates.certs.certificates[length(data.oci_load_balancer_certificates.certs.certificates) - 1]["certificate_name"]
│     ├────────────────
│     │ data.oci_load_balancer_certificates.certs.certificates is empty list of object
│ 
│ The given key does not identify an element in this collection value: a negative number is not a valid index for a sequence.`

Also, quick update about my last issue : I did create a new OCI account and I can create NAT Gateways now

**Comment by bkk87** [comment]
thanks for fixing it using dynamic blocks!
